# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-server:
    machine: true
    working_directory: ~/hybread/server
    steps:
      - checkout:
          path: ~/hybread
      - run:
          name: Docker Build
          command: docker build -t panchem/hybread:$CIRCLE_BUILD_NUM .
      - run:
          name: Docker Push
          command: |
            docker login -u $DOCKER_UNAME -p $DOCKER_PWORD
            docker push panchem/hybread:$CIRCLE_BUILD_NUM
  build-client:
    docker:
      - image: circleci/node:8-stretch-browsers
    working_directory: ~/hybread/client
    steps:
      - checkout:
          path: ~/hybread
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Packages
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - yarn.lock
      - run:
          name: Build
          command: yarn build
      - deploy:
          name: Deploy
          command: |
            export TARGET_BRANCH=gh-pages
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

            git clone $CIRCLE_REPOSITORY_URL out

            cd out
            git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
            git rm -rf .
            cd ..

            cp -a dist/client/. out/.
            mkdir -p out/.circleci && cp -a ../.circleci/. out/.circleci/.

            cd out
            cp index.html 404.html
            echo hybread.io > CNAME

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

            git push https://$GH_TOKEN@github.com/calebhiebert/hybread.git $TARGET_BRANCH -q
  deploy-server:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          finterprints:
            - 'cc:1e:3f:53:0e:d9:a9:66:b4:a1:ad:32:f9:50:d3:56'
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "/root/hybread/deploy.sh $CIRCLE_BUILD_NUM"
workflows:
  version: 2
  client:
    jobs:
      - build-client:
          filters:
            branches:
              only: master
  server:
    jobs:
      - build-server:
          filters:
            branches:
              only: master
      - deploy-server:
          requires:
            - build-server
          filters:
            branches:
              only: master
