# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-server:
    docker:
      # specify the version
      - image: circleci/golang:1.10-stretch
    environment:
      - GOCACHE: '/tmp/go/cache'
      - DEP_VERSION: 0.5.0
    working_directory: /go/src/github.com/calebhiebert/hybread/server
    steps:
      - checkout:
          path: /go/src/github.com/calebhiebert/hybread
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/calebhiebert/hybread/vendor

      - run:
          name: download-libraries
          command: |
            if [ ! -d /go/src/github.com/calebhiebert/hybread/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi

      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/calebhiebert/hybread/vendor
      - run:
          name: test
          command: |
            mkdir -p $GOCACHE
            export GOOS=linux
            export GOARCH=amd64
            go build -v -o hybread

            export GOOS=windows
            export GOARCH=amd64
            go build -v -o hybread.exe

      - store_artifacts:
          path: ./hybread
      - store_artifacts:
          path: ./hybread.exe
  build-client:
    docker:
      - image: circleci/node:8-stretch-browsers
    working_directory: ~/hybread/client
    steps:
      - checkout:
          path: ~/hybread
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Packages
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - yarn.lock
      - run:
          name: Build
          command: yarn build
      - deploy:
          name: Deploy
          command: |
            export TARGET_BRANCH=gh-pages
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

            git clone $CIRCLE_REPOSITORY_URL out

            cd out
            git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
            git rm -rf .
            cd ..

            cp -a dist/client/. out/.
            mkdir -p out/.circleci && cp -a ../.circleci/. out/.circleci/.

            cd out
            cp index.html 404.html
            echo hybread.io > CNAME

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

            git push https://$GH_TOKEN@github.com/calebhiebert/hybread.git $TARGET_BRANCH -q
workflows:
  version: 2
  build:
    jobs:
      - build-client:
          filters:
            branches:
              only: master
      - build-server:
          filters:
            branches:
              only: master
