version: '3'
services:
  # PostgreSQL
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: hybread
  # Redis
  redis:
    restart: always
    image: redis:5-alpine
  # App
  hybread:
    image: panchem/hybread:${IMAGE_TAG}
    restart: always
    depends_on:
      - db
      - redis
    labels:
      - 'traefik.backend=be'
      - 'traefik.docker.network=proxy'
      - 'traefik.enable=true'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:api.hybread.io'
      - 'traefik.default.protocol=http'
      - 'traefik.frontend.priority=20'
    environment:
      PG_HOST: db
      PG_USER: hybread
      PG_PASS: $POSTGRES_PASSWORD
      RD_HOST: redis:6379
networks:
  default:
    external:
      name: proxy
