/*
	schema.sql.go

	This file contains the database schema
*/
package main

func GetDropSchema() string {
	return `
	DROP TABLE "user_items";
		DROP TABLE "users";
		DROP TABLE "items";
	`
}

func GetSchema() string {
	return `
    CREATE TABLE IF NOT EXISTS "users" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "username" VARCHAR(32) UNIQUE NOT NULL,
			"password" VARCHAR(64) NOT NULL,
			"currency" INTEGER NOT NULL CHECK (currency >= 0)
		);
		

		DO $$ BEGIN
			CREATE TYPE ITEM_CATEGORY AS ENUM('tool', 'heat-source', 'cooking-surface', 'base-ingredient', 'extra-ingredient');
		EXCEPTION
			WHEN duplicate_object THEN null;
		END $$;
		
		CREATE TABLE IF NOT EXISTS "items" (
			"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"name" VARCHAR(32) UNIQUE NOT NULL,
			"category" ITEM_CATEGORY NOT NULL,
			"description" TEXT NOT NULL,
			"cost" INTEGER NOT NULL CHECK (cost >= 0)
		);

		CREATE TABLE IF NOT EXISTS "user_items" (
			"user_id" INTEGER NOT NULL REFERENCES users(id),
			"item_id" INTEGER NOT NULL REFERENCES items(id),
			"count" INTEGER NOT NULL,

			PRIMARY KEY ("user_id", "item_id")
		)
	`
}
